name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code
      - name: Install Docker and Docker Compose
        run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose  # Install Docker Compose
      - name: Setup Docker-Compose
        run: |
            docker-compose up -d  # Start the services in detached mode
        
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"  # Run tests
        
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"  # Lint the code
